# Generated by Django 2.2.3 on 2019-07-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200)),
                ('stock_price', models.IntegerField()),
                ('stock_to_sell', models.IntegerField()),
            ],
        ),
    ]
